M48
; DRILL file {KiCad 7.0.10} date Tuesday, January 23, 2024 at 06:03:34 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-23T18:03:34-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0335
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0400
%
G90
G05
T1
X3.15Y-3.75
X3.15Y-4.05
X4.05Y-3.75
X4.05Y-4.05
T2
X4.5Y-4.7031
X4.5Y-4.8016
X4.5Y-4.9
T3
X4.7Y-3.4
X4.7Y-4.0
X4.8Y-3.4
X4.8Y-4.0
X4.9Y-3.4
X4.9Y-4.0
X5.0Y-3.4
X5.0Y-4.0
X5.1Y-3.4
X5.1Y-4.0
X5.2Y-3.4
X5.2Y-4.0
X5.3Y-3.4
X5.3Y-4.0
M30
